sudo: required
language: python
python: "3.7"
dist: xenial
services:
  - redis-server
  - mysql
  - postgresql
  - docker
env:
  - TOXENV=py27
  - TOXENV=py37
  - TOXENV=lint
matrix:
  include:
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
install:
  - pip install tox coveralls
before_script:
  - mysql -e 'create database test;'
  - docker run -d --name pypi-ldap -p 389:389 -v "$TRAVIS_BUILD_DIR/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom" osixia/openldap --copy-service
script: tox
after_success:
  if [ "$TOXENV" == "py36" ]; then coveralls; fi
